development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://mkmtkdnhheadli:6m0EwZTq77CAx8WYzc3x0NxKlV@ec2-23-21-157-223.compute-1.amazonaws.com:5432/d703decokbpsei
