# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8841c5c9ee62817d0601f9331b18416bff6e1346994e1133f32d4d8f6f3d9c369c93949e1af1bce09f76145da5511b116c23cc4ca5298f436b0b36d4ce8d93cd

test:
  secret_key_base: 70212c6f926f951a98ff396040b54513f50f6f981d296a5c40ecbbd49ffa47dd165beaa8973b31f78f527928b9f1d5dbca0fe1895b4b29a27c7c6a9419120d21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
